# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python
python:
  - 2.7
  - 3.4
  - 3.5

cache: pip

install: pip install tox tox-travis

script: tox

notifications:
  email: false
